import { useEffect, useState } from 'react';
import Head from 'next/head';
import NavBar from '../frontend/components/NavBar/NavBar';
import '@/styles/globals.scss';
import '../frontend/components/Calendar/Calendar.scss';
import '../pages/Dashboard/Dashboard.scss';
import '../frontend/components/NavBar/NavBar.scss';

export default function App({ Component, pageProps }) {
   const [render, setRender] = useState(false);
   useEffect(() => setRender(true), []);
   if (typeof window === 'undefined') return null;
   return render ? (
      <>
         <Head>
            <title>Money Manager</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/money-mgr-favicon.ico" />
         </Head>
         <NavBar />
         <Component {...pageProps} />
      </>
   ) : null;
}
