import Head from 'next/head'
import NavBar from '@/frontend/components/NavBar/NavBar';
import Dashboard from '../pages/Dashboard/Dashboard';
import Accounts from '../pages/Accounts/Accounts';
import styles from '@/styles/Home.module.scss';
import { useRouter } from 'next/router';

export default function Home() {
   const router = useRouter();
   const currentPath = router.pathname;

   return (
      <>
         <Head>
            <title>Money Manager</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/money-mgr-favicon.ico" />
         </Head>
         <main className={styles.main}>
            {currentPath === '/' && <Dashboard />}
            {currentPath === '/about' && <About />}
            {currentPath === '/accounts' && <Accounts />}
         </main>
      </>
   )
}
