import Head from 'next/head'
import Link from 'next/link';
import Calendar from '../components/Calendar';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Money Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/money-mgr-favicon.ico" />
      </Head>
      <main className={styles.main}>
         <Calendar />
      </main>
    </>
  )
}
