import Head from 'next/head'
import NavBar from '@/frontend/components/NavBar/NavBar';
import Calendar from '../frontend/components/Calendar/Calendar';
import styles from '@/styles/Home.module.scss';
import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom';

export default function Home() {
   const time = Date.now();
   const date = new Date(time);
   const year = date.getFullYear();
   const month = date.getMonth() + 1;
   const today = date.getDate();

   return (
      <>
         <Head>
            <title>Money Manager</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/money-mgr-favicon.ico" />
         </Head>
         <NavBar />
         <main className={styles.main}>
            <Router>
               <Routes>
                  <Route path="/" element={<Calendar year={year} month={month} today={today} />} />
               </Routes>
            </Router>
         </main>
      </>
   )
}
